name: darlink
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_blob: ^0.0.1
  flutter_bloc: ^9.1.0
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  agora_rtc_engine: ^6.5.1
  google_maps_flutter: ^2.12.1
  panorama_viewer: ^2.0.4
  image_picker: ^1.1.2
  mongo_dart: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
